# -*- coding: utf-8 -*-
"""evaluate

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cmDeoOKTjm4Mybf8rCFf8gFlhABPPXF6
"""

import pandas as pd
import joblib

from sklearn.model_selection import train_test_split

from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

df = pd.read_csv(
    "processed_churn.csv"
)

X = df.drop(
    "Churn",
    axis=1
)

y = df["Churn"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

model = joblib.load(
    "churn_classifier.pkl"
)

print("Model loaded")

y_pred = model.predict(
    X_test
)

y_prob = model.predict_proba(
    X_test
)[:,1]

accuracy = accuracy_score(
    y_test,
    y_pred
)

precision = precision_score(
    y_test,
    y_pred
)

recall = recall_score(
    y_test,
    y_pred
)

f1 = f1_score(
    y_test,
    y_pred
)

roc_auc = roc_auc_score(
    y_test,
    y_prob
)

print("Accuracy:", round(accuracy,2))
print("Precision:", round(precision,2))
print("Recall:", round(recall,2))
print("F1-score:", round(f1,2))
print("ROC-AUC:", round(roc_auc,2))

cm = confusion_matrix(
    y_test,
    y_pred
)

tn, fp, fn, tp = cm.ravel()

print(
    "True Negative:",
    tn
)

print(
    "False Positive:",
    fp
)

print(
    "False Negative:",
    fn
)

print(
    "True Positive:",
    tp
)

print(
    classification_report(
        y_test,
        y_pred
    )
)

print(
    "Model evaluation completed."
)

print(
    "Evaluation metrics generated successfully."
)

"""Model Evaluation Interpretation

The model achieved an overall accuracy of 82%.

It performed very well in identifying non-churn customers with a recall of 90%.

For churn prediction, the model achieved 69% precision and 60% recall, indicating that many churn customers were correctly identified, although some were still missed.

Future improvements may focus on increasing recall because detecting churn customers is important for business retention strategies.
"""