# -*- coding: utf-8 -*-
"""predict

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QeRfXhM-Q4EsMwnrSGc029mbDxPsEoyL
"""

import pandas as pd
import joblib

model = joblib.load(
    "churn_classifier.pkl"
)

print("Model loaded successfully")

def predict_churn(customer_data):

    sample = pd.DataFrame(
        [customer_data]
    )

    prediction = model.predict(
        sample
    )[0]

    probability = model.predict_proba(
        sample
    )[0][1]


    if probability < 0.40:
        risk = "Low Risk"

    elif probability < 0.70:
        risk = "Medium Risk"

    else:
        risk = "High Risk"


    if prediction == 1:
        result = "Customer likely to churn"

    else:
        result = "Customer likely to stay"


    print("\nPrediction:", result)

    print(
        "Churn Probability:",
        round(probability,2)
    )

    print(
        "Risk Level:",
        risk
    )

def predict_churn():

    print("\nENTER CUSTOMER DETAILS\n")


    senior = int(
        input(
            "Senior Citizen (0=No, 1=Yes): "
        )
    )


    print("Typical dataset range: 0–72")

    tenure = int(
        input(
            "Tenure (months): "
        )
    )


    print("Typical dataset range: 18–120")

    monthly = float(
        input(
            "Monthly Charges: "
        )
    )


    print("Typical dataset range: 0–8700")

    total = float(
        input(
            "Total Charges: "
        )
    )


    gender = input(
        "Gender (Male/Female): "
    ).lower()


    partner = input(
        "Partner? (Yes/No): "
    ).lower()


    dependents = input(
        "Dependents? (Yes/No): "
    ).lower()



    sample = {

        'SeniorCitizen':
        senior,

        'tenure':
        tenure,

        'MonthlyCharges':
        monthly,

        'TotalCharges':
        total,


        'gender_Male':
        1 if gender=="male" else 0,

        'Partner_Yes':
        1 if partner=="yes" else 0,

        'Dependents_Yes':
        1 if dependents=="yes" else 0,

        'PhoneService_Yes':
        1,

        'MultipleLines_No phone service':
        0,

        'MultipleLines_Yes':
        1,

        'InternetService_Fiber optic':
        1,

        'InternetService_No':
        0,

        'OnlineSecurity_No internet service':
        0,

        'OnlineSecurity_Yes':
        0,

        'OnlineBackup_No internet service':
        0,

        'OnlineBackup_Yes':
        1,

        'DeviceProtection_No internet service':
        0,

        'DeviceProtection_Yes':
        0,

        'TechSupport_No internet service':
        0,

        'TechSupport_Yes':
        0,

        'StreamingTV_No internet service':
        0,

        'StreamingTV_Yes':
        1,

        'StreamingMovies_No internet service':
        0,

        'StreamingMovies_Yes':
        1,

        'Contract_One year':
        0,

        'Contract_Two year':
        0,

        'PaperlessBilling_Yes':
        1,

        'PaymentMethod_Credit card (automatic)':
        0,

        'PaymentMethod_Electronic check':
        1,

        'PaymentMethod_Mailed check':
        0
    }


    sample = pd.DataFrame(
        [sample]
    )


    pred = model.predict(
        sample
    )[0]



    prob = model.predict_proba(
        sample
    )[0][1]



    if prob < 0.40:
        risk = "Low Risk"

    elif prob < 0.70:
        risk = "Medium Risk"

    else:
        risk = "High Risk"



    print("\nRESULT")

    if pred==1:
        print(
            "Prediction: Customer likely to churn"
        )

    else:
        print(
            "Prediction: Customer likely to stay"
        )


    print(
        "Probability:",
        round(prob,2)
    )

    print(
        "Risk:",
        risk
    )

predict_churn()