# -*- coding: utf-8 -*-
"""preprocess.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fC8N3vKigWHwa6g1SQx_7_mqeAcIKZon
"""

import pandas as pd

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

df=pd.read_csv("/content/WA_Fn-UseC_-Telco-Customer-Churn.csv")
print("Customer Churn data set loaded successfully!")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

for col in df.columns:
    print(col, ":", df[col].nunique())

print("Total unique rows in the dataset:", df.drop_duplicates().shape[0])

# since total unique rows and total customerid is the same
# we remove customerid since it is useless

df.drop("customerID", axis=1, inplace=True)
print('"customerID" column removed successfully!')

df['TotalCharges'].unique()
# here, Totalcharges column has 6531 unique numerical values.

# but total charges is stored as object so we need to change it
df.info()

# changing totalcharges to numerical data

df["TotalCharges"] = pd.to_numeric(
    df["TotalCharges"],
    errors="coerce"
)

df.info()

print(df.isnull().sum())

# i think, Totalcharges is null when tenure = 0

df[df["TotalCharges"].isnull()][["tenure","MonthlyCharges","TotalCharges"]]

# total charges is 0 for customers when tenure = 0
# so we fill Totalcharges with 0, instead of median
# since when tenure = 0, the customer has no charges

df["TotalCharges"] = df["TotalCharges"].fillna(0)
print("Missing Totalcharges handled by equating = 0")

# see how min value of Totalcharges is 0
df.describe()

# set target column to (0/1) instead of (yes/no)

le = LabelEncoder()

df["Churn"] = le.fit_transform(
    df["Churn"]
)

# set y = target and X as input

y = df["Churn"]
X = df.drop("Churn", axis=1)

categorical_cols = X.select_dtypes(
    include="object"
).columns

print(categorical_cols)

numerical_cols = X.select_dtypes(
    exclude="object"
).columns

print(numerical_cols)

# encoding categorical columns to numerical
# so categorical columns = null

X = pd.get_dummies(
    X,
    drop_first=True
)
print("Showing categorical columns")
categorical_cols = X.select_dtypes(
    include="object"
).columns

print(categorical_cols)

scaler = StandardScaler()

X[numerical_cols] = scaler.fit_transform(
    X[numerical_cols]
)

df.describe()

df.info()
print("")
print("Original features:", df.drop('Churn', axis=1).shape[1])
print("Features after encoding:", X.shape[1])

print(
    "Original rows:",
    len(df)
)

print(
    "Rows after cleaning:",
    len(X)
)

print(
    "Target column: Churn"
)

print(
    "Input features:",
    X.shape[1]
)

print(
    "Missing values:",
    X.isnull().sum().sum()
)